# Generated by Django 3.0.7 on 2020-06-22 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_remove_stamp_noteid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
