# Generated by Django 3.0.7 on 2020-06-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_stamp_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='mood',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='notes',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='title',
            field=models.CharField(default=models.CharField(max_length=10), max_length=25),
        ),
    ]
