# Generated by Django 3.0.7 on 2020-07-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_auto_20200702_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noter',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
