# Generated by Django 3.0.8 on 2020-07-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0017_auto_20200703_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='notes',
            field=models.CharField(max_length=250),
        ),
    ]
